plugin_repo(
    name = "e2e",
    plugin = "plugin-integration-testing",
    revision="b9b913ed4b13aac4b921e70c716fca6615eb681a"
)

plugin_repo(
    name = "cc",
    plugin = "cc-rules",
    revision="v0.3.2"
)

plugin_repo(
  name = "shell",
  revision = "v0.1.2",
)
