plugin_repo(
    name = "e2e",
    plugin = "plugin-integration-testing",
    revision = "v1.0.3",
)

plugin_repo(
    name = "cc",
    revision = "v0.3.2",
)

plugin_repo(
    name = "shell",
    revision = "v0.1.2",
)

plugin_repo(
    name = "go",
    revision = "master",
)
