filegroup(
    name = "go",
    srcs = ["go.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "cgo",
    srcs = ["cgo.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "go_deps",
    srcs = ["go_deps.build_defs"],
    visibility = ["PUBLIC"],
)
