subinclude("//build_defs:go")

go_test(
    name = "buildinfo_test",
    srcs = ["buildinfo_test.go"],
    data = ["//tools/please_go"],
    deps = [
        "///third_party/go/github.com_stretchr_testify//assert",
    ],
)
