filegroup(
    name = "test_go_mod_files",
    srcs = [
        "host_go_mod",
        "invalid_go_mod",
        "module_go_mod",
    ],
    test_only = True,
    visibility = ["//tools/please_go/generate/..."],
)
