subinclude("//test/build_defs:e2e")

please_repo_e2e_test(
    name = "structured_test",
    plz_command = "plz test",
    repo = "structured_repo",
)

please_repo_e2e_test(
    name = "unstructured_test",
    plz_command = "plz test",
    repo = "unstructured_repo",
)
